# fly.toml app configuration file generated for openrouter-proxy-injector
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'openrouter-proxy-injector'
primary_region = 'sin'

[build]

[env]
  UVICORN_HOST = '0.0.0.0'
  UVICORN_PORT = '8080'
  TIMEZONE = 'UTC'
  UVICORN_LOG_LEVEL = 'info'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
